export const dinodb = [
  {
    name: "Paraplacodus",
    location: "Italy",
    type: "Placodonts",
    meaning: "Almost Placodus",
    period: "Triassic",
    diet: "Shellfish",
    size: "1.5m",
  },
  {
    name: "Placodus",
    location: "Germany",
    type: "Placodonts",
    meaning: "Flat toothed",
    period: "Triassic",
    diet: "Shellfish",
    size: "3m",
  },
  //   {
  //     name: "Cyamodus",
  //     location: "Germany",
  //     type: "Placodonts",
  //     meaning:
  //     period: "Triassic",
  //     diet: "Shellfish",
  //     size: "1.3m",
  //   },
  {
    name: "Henodus",
    location: "Germany",
    type: "Placodonts",
    meaning: "Armoured",
    period: "Triassic",
    diet: "Shellfish",
    size: "1m",
  },
  //   {
  //     name: "Cymbospondylus",
  //     location: "USA, Germany",
  //     type: "Ichthyosaurs",

  //     period: "Triassic",
  //     diet: "Fish",
  //     size: "6m",
  //   },
  {
    name: "Mixosaurus",
    location: "China, Timor, Indonesia, Italy, Canada, USA, Norway",
    type: "Ichthyosaurs",
    meaning: "Mixed Lizard",
    period: "Triassic",
    diet: "Fish",
    size: "1m",
  },
  {
    name: "Shonisaurus",
    location: "USA, Canada",
    type: "Ichthyosaurs",
    meaning: "Lizard from the Shoshone Mountains",
    period: "Triassic",
    diet: "Fish",
    size: "15m",
  },
  {
    name: "Utatsusaurus",
    location: "Japan, Canada",
    type: "Ichthyosaurs",
    meaning: "Lizard from Utatsugyoryu in Japan",
    period: "Triassic",
    diet: "Fish",
    size: "3m",
  },
  {
    name: "Ceresiosaurus",
    location: "Europe",
    type: "Nothosaurs",
    meaning: "Lizard of Ceres",
    period: "Triassic",
    diet: "Fish",
    size: "4m",
  },
  {
    name: "Nothosaurus",
    location: "Europe, North Africa, Russia, China",
    type: "Nothosaurs",
    meaning: "False Lizard",
    period: "Triassic",
    diet: "Fish",
    size: "3m",
  },
  {
    name: "Pachypleurosaurus",
    location: "Italy, Romania, Switzerland",
    type: "Nothosaurs",
    meaning: "Thick Rib Lizard",
    period: "Triassic",
    diet: "Fish",
    size: "1m",
  },
  {
    name: "Lariosaurus",
    location: "Spain, France, Italy, Germany, Switzerland, China",
    type: "Nothosaurs",
    meaning: "Lizard from Lake Lario",
    period: "Triassic",
    diet: "Fish, Shellfish",
    size: "60cm",
  },
  {
    name: "Sharovipteryx",
    location: "Kyrgyzstan",
    type: "Pterosaurs",
    meaning: "Sharov's wing",
    period: "Triassic",
    diet: "Insects",
    size: "30cm",
  },
  {
    name: "Eudiomorphodon",
    location: "Italy",
    type: "Pterosaurs",
    meaning: "True Two-Formed Tooth",
    period: "Triassic",
    diet: "Fish",
    size: "1m",
  },
  {
    name: "Peteinosaurus",
    location: "Italy",
    type: "Pterosaurs",
    meaning: "Winged Lizard",
    period: "Triassic",
    diet: "Insects",
    size: "60cm",
  },
  {
    name: "Preondactylus",
    location: "Italy",
    type: "Pterosaurs",
    meaning: "Finger from the Preone Valley",
    period: "Triassic",
    diet: "Fish",
    size: "1.5m",
  },
  {
    name: "Eoraptor",
    location: "Argentina",
    type: "Therapods",
    meaning: "Dawn Plunderer",
    period: "Triassic",
    diet: "Meat",
    size: "1m",
  },
  {
    name: "Herrerasaurus",
    location: "Argentina",
    type: "Therapods",
    meaning: "From Herrera",
    period: "Triassic",
    diet: "Meat",
    size: "5m",
  },
  {
    name: "Chindesaurus",
    location: "USA",
    type: "Therapods",
    meaning: "From Chinde Point",
    period: "Triassic",
    diet: "Meat",
    size: "3m",
  },
  {
    name: "Staurikosaurus",
    location: "Brazil",
    type: "Therapods",
    meaning: "From the Southern Cross constellation",
    period: "Triassic",
    diet: "Meat",
    size: "2m",
  },
  {
    name: "Aliwalia",
    location: "South Africa",
    type: "Therapods",
    meaning: "From Aliwalia in South Africa",
    period: "Triassic",
    diet: "Meat",
    size: "8m",
  },
  {
    name: "Shuvosaurus",
    location: "USA",
    type: "Therapods",
    meaning: "From Shuvo",
    period: "Triassic",
    diet: "Omnivorous",
    size: "3m",
  },
  {
    name: "Gojirasaurus",
    location: "USA",
    type: "Therapods",
    meaning: "From Gojira",
    period: "Triassic",
    diet: "Meat",
    size: "5.5m",
  },
  {
    name: "Liliensternus",
    location: "Germany",
    type: "Therapods",
    meaning: "From Ruhle von Lilienstern",
    period: "Triassic",
    diet: "Meat",
    size: "5m",
  },
  {
    name: "Procompsognathus",
    location: "Germany",
    type: "Therapods",
    meaning: "Before Compsognathus",
    period: "Triassic",
    diet: "Meat",
    size: "1.2m",
  },
  {
    name: "Camposaurus",
    location: "USA",
    type: "Therapods",
    meaning: "From Charles Lewis Camp",
    period: "Triassic",
    diet: "Meat",
    size: "1m",
  },
  {
    name: "Coelophysis",
    location: "USA",
    type: "Therapods",
    meaning: "Hollow Form",
    period: "Triassic",
    diet: "Meat",
    size: "2.7m",
  },
  {
    name: "Eucoelophysis",
    location: "USA",
    type: "Therapods",
    meaning: "True Coelophysis",
    period: "Triassic",
    diet: "Meat",
    size: "3m",
  },
  {
    name: "Saturnalia",
    location: "Brazil",
    type: "Sauropodomorphs",
    meaning: "After the Roman Solstice Festival",
    period: "Triassic",
    diet: "Plants",
    size: "1.5m",
  },
  {
    name: "Thecodontosaurus",
    location: "England, Wales",
    type: "Sauropodomorphs",
    meaning: "Socket-Toothed Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "2m",
  },
  {
    name: "Efraasia",
    location: "Germany",
    type: "Sauropodomorphs",
    meaning: "After Eberhard Fraas",
    period: "Triassic",
    diet: "Plants",
    size: "2.4m",
  },
  {
    name: "Sellosaurus",
    location: "Germany",
    type: "Sauropodomorphs",
    meaning: "Graceful Saddle Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "6.5m",
  },
  {
    name: "Euskelosaurus",
    location: "Lesotho, South Africa, Zimbabwe",
    type: "Prosauropods",
    meaning: "Well-limbed Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "9-12m",
  },
  {
    name: "Blikanansaurus",
    location: "Lesotho",
    type: "Prosauropods",
    meaning: "Lizard from Blikana",
    period: "Triassic",
    diet: "Plants",
    size: "5m",
  },
  {
    name: "Plateosaurus",
    location: "Germany, Switzerland, France",
    type: "Prosauropods",
    meaning: "Broad Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "8m",
  },
  {
    name: "Lessemsaurus",
    location: "Argentina",
    type: "Prosauropods",
    meaning: "Lessem's Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "9m",
  },
  {
    name: "Riojasaurus",
    location: "Argentina",
    type: "Prosauropods",
    meaning: "Lizard from Rioja province",
    period: "Triassic",
    diet: "Plants",
    size: "11m",
  },
  {
    name: "Camelotia",
    location: "England",
    type: "Prosauropods",
    meaning: "From Camelot",
    period: "Triassic",
    diet: "Plants",
    size: "9m",
  },
  {
    name: "Melanorosaurus",
    location: "South Africa",
    type: "Prosauropods",
    meaning: "Black Mountain Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "15m",
  },
  {
    name: "Pisanosaurus",
    location: "Argentina",
    type: "Ornithopods",
    meaning: "Pisano's Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "1m",
  },
  {
    name: "Technosaurus",
    location: "USA",
    type: "Ornithopods",
    meaning: "Texa University Lizard",
    period: "Triassic",
    diet: "Plants",
    size: "1m",
  },
  {
    name: "Antetonitrus",
    location: "South Africa",
    type: "Sauropodomorphs",
    meaning: "Before the Thunder",
    period: "Triassic",
    diet: "Plants",
    size: "10m",
  },
  {
    name: "Isanosaurus",
    location: "Thailand",
    type: "Sauropodomorphs",
    meaning: "Lizard of Isan",
    period: "Triassic",
    diet: "Plants",
    size: "6m",
  },
  {
    name: "Temnodontosaurus",
    location: "England, Germany",
    type: "Ichthyosaurs",
    meaning: "Cutting Toothed Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "10m",
  },
  {
    name: "Ichthyosaurus",
    location: "England",
    type: "Ichthyosaurs",
    meaning: "Fish Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "2m",
  },
  {
    name: "Excalibosaurus",
    location: "England",
    type: "Ichthyosaurs",
    meaning: "Excalibur Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "7m",
  },
  {
    name: "Opthalmosaurus",
    location: "England, France, North America, Canada, Argentina",
    type: "Ichthyosaurs",
    meaning: "Eye Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "3.5m",
  },
  {
    name: "Macroplata",
    location: "Europe",
    type: "Plesiosaurs",
    meaning: "Big Plate",
    period: "Early Jurassic",
    diet: "Fish",
    size: "5m",
  },
  {
    name: "Rhomaleosaurus",
    location: "England, Germany",
    type: "Plesiosaurs",
    meaning: "Strong Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "6m",
  },
  {
    name: "Attenborosaurus",
    location: "Europe",
    type: "Plesiosaurs",
    meaning: "Attenborough's Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "5m",
  },
  {
    name: "Plesiosaurus",
    location: "Europe",
    type: "Plesiosaurs",
    meaning: "Almost a Lizard",
    period: "Early Jurassic",
    diet: "Fish",
    size: "3.5m",
  },
  {
    name: "Dimorphodon",
    location: "England",
    type: "Pterosaurs",
    meaning: "Two Types of Teeth",
    period: "Early Jurassic",
    diet: "Fish",
    size: "1.4m",
  },
  {
    name: "Campylognathoides",
    location: "Germany, India",
    type: "Pterosaurs",
    meaning: "Like the Curved Jaw",
    period: "Early Jurassic",
    diet: "Fish",
    size: "1.75m",
  },
  {
    name: "Dorygnathus",
    location: "Germany",
    type: "Pterosaurs",
    meaning: "Spear Jaw",
    period: "Early Jurassic",
    diet: "Fish",
    size: "1m",
  },
  {
    name: "Parapsicephalus",
    location: "England, Germany",
    type: "Pterosaurs",
    meaning: "Almost an Arched Head",
    period: "Early Jurassic",
    diet: "Fish",
    size: "1m",
  },
  {
    name: "Dilophosaurus",
    location: "USA, China",
    type: "Therapods",
    meaning: "Lizard with Two Crests",
    period: "Early Jurassic",
    diet: "Meat",
    size: "6m",
  },
  {
    name: "Segisaurus",
    location: "USA",
    type: "Therapods",
    meaning: "Lizard from the Segi Canyon",
    period: "Early Jurassic",
    diet: "Meat",
    size: "1m",
  },
  {
    name: "Podokesaurus",
    location: "USA",
    type: "Therapods",
    meaning: "Swift Foot Lizard",
    period: "Early Jurassic",
    diet: "Meat",
    size: "1m",
  },
  {
    name: "Syntarsus",
    location: "Zimbabwe",
    type: "Therapods",
    meaning: "Fused Ankle",
    period: "Early Jurassic",
    diet: "Meat",
    size: "2m",
  },
  {
    name: "Sarcosaurus",
    location: "England",
    type: "Therapods",
    meaning: "Flesh-eating Lizard",
    period: "Early Jurassic",
    diet: "Meat",
    size: "3.5m",
  },
  {
    name: "Saltriosaurus",
    location: "Italy",
    type: "Therapods",
    meaning: "Lizard from Saltrio",
    period: "Early Jurassic",
    diet: "Meat",
    size: "8m",
  },
  {
    name: "Cryolophosaurus",
    location: "Antartica",
    type: "Therapods",
    meaning: "Frozen Crested Lizard",
    period: "Early Jurassic",
    diet: "Meat",
    size: "6m",
  },
  {
    name: "Anchisaurus",
    location: "USA",
    type: "Prosauropods",
    meaning: "Near Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "2.5m",
  },
  {
    name: "Jingshanosaurus",
    location: "China",
    type: "Prosauropods",
    meaning: "Lizard from Golden Hill",
    period: "Early Jurassic",
    diet: "Plants",
    size: "9.8m",
  },
  {
    name: "Yunnanosaurus",
    location: "China",
    type: "Prosauropods",
    meaning: "Lizard from Yunnan",
    period: "Early Jurassic",
    diet: "Plants",
    size: "7m",
  },
  {
    name: "Massospondylus",
    location: "Lesotho, Namibia, South Africa, Zimbabwe",
    type: "Prosauropods",
    meaning: "Massive Vertebra",
    period: "Early Jurassic",
    diet: "Plants",
    size: "4m",
  },
  {
    name: "Kunmingosaurus",
    location: "China",
    type: "Sauropods",
    meaning: "Lizard from Kunming",
    period: "Early Jurassic",
    diet: "Plants",
    size: "11m",
  },
  {
    name: "Kotasaurus",
    location: "India",
    type: "Sauropods",
    meaning: "Lizard from Kota Province",
    period: "Early Jurassic",
    diet: "Plants",
    size: "9m",
  },
  {
    name: "Vulcanodon",
    location: "Zimbabwe",
    type: "Sauropods",
    meaning: "Volcano Tooth",
    period: "Early Jurassic",
    diet: "Plants",
    size: "6.5m",
  },
  {
    name: "Barapasaurus",
    location: "India",
    type: "Sauropods",
    meaning: "Big Legged Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "18m",
  },
  {
    name: "Lesothosaurus",
    location: "Lesotho, South Africa",
    type: "Ornithopods",
    meaning: "Lizard from Lesotho",
    period: "Early Jurassic",
    diet: "Plants",
    size: "1m",
  },
  {
    name: "Abrictosaurus",
    location: "Lesotho, South Africa",
    type: "Ornithopods",
    meaning: "Wide-awake Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "1.2m",
  },
  {
    name: "Lanasaurus",
    location: "South Africa",
    type: "Ornithopods",
    meaning: "Woolly Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "1.2m",
  },
  {
    name: "Heterodontosaurus",
    location: "South Africa",
    type: "Ornithopods",
    meaning: "Differently-toothed Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "1m",
  },
  {
    name: "Scutellosaurus",
    location: "USA",
    type: "Thyreophora",
    meaning: "Little Shield Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "1.2m",
  },
  {
    name: "Scelidosaurus",
    location: "England",
    type: "Thyreophora",
    meaning: "Leg Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "4m",
  },
  {
    name: "Emausaurus",
    location: "Germany",
    type: "Thyreophora",
    meaning: "Acronym for Ernst-Moritz-Arndt Universitat Lizard",
    period: "Early Jurassic",
    diet: "Plants",
    size: "2m",
  },
  {
    name: "Lusitanosaurus",
    location: "Portugal",
    type: "Thyreophora",
    meaning: "Lizard from Lusitania",
    period: "Early Jurassic",
    diet: "Plants",
    size: "4m",
  },
  {
    name: "Megalosaurus",
    location: "France, Portugal",
    type: "Therapods",
    meaning: "Big Lizard",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "9m",
  },
  {
    name: "Eustreptospondylus",
    location: "England",
    type: "Therapods",
    meaning: "Well-curved Vertebrae",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "9m",
  },
  {
    name: "Poekilopleuron",
    location: "France",
    type: "Therapods",
    meaning: "Varying Side",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "9m",
  },
  {
    name: "Magnosaurus",
    location: "England",
    type: "Therapods",
    meaning: "Huge Lizard",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "4m",
  },
  {
    name: "Ozraptor",
    location: "Australia",
    type: "Therapods",
    meaning: "Australian Lizard",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "3m",
  },
  {
    name: "Kaijiangosaurus",
    location: "China",
    type: "Therapods",
    meaning: "Lizard from Kaijiang River",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "6m",
  },
  {
    name: "Piatnitzkysaurus",
    location: "Argentina",
    type: "Therapods",
    meaning: "Piatnitzky's Lizard",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "4.3m",
  },
  {
    name: "Proceratosaurus",
    location: "England",
    type: "Therapods",
    meaning: "Before Ceratosaurus",
    period: "Middle Jurassic",
    diet: "Meat",
    size: "2m",
  },
  {
    name: "Omeisaurus",
    location: "China",
    type: "Sauropods",
    meaning: "Lizard from Mount Omei",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "15m",
  },
  {
    name: "Shunosaurus",
    location: "China",
    type: "Sauropods",
    meaning: "Sichuan Lizard",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "9m",
  },
  {
    name: "Mamenchisaurus",
    location: "China, Mongolia",
    type: "Sauropods",
    meaning: "Lizard from Mamen Brook",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "21m",
  },
  {
    name: "Datousaurus",
    location: "China",
    type: "Sauropods",
    meaning: "Chieftan Lizard",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "15m",
  },
  {
    name: "Cetiosaurus",
    location: "England, Portugal, Morocco",
    type: "Sauropods",
    meaning: "Whale Lizard",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "14m",
  },
  {
    name: "Amygdalodon",
    location: "Argentina",
    type: "Sauropods",
    meaning: "Almond-shaped Tooth",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "13m",
  },
  {
    name: "Patagosaurus",
    location: "Argentina",
    type: "Sauropods",
    meaning: "Lizard from Patagonia",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "18m",
  },
  {
    name: "Yandusaurus",
    location: "China",
    type: "Ornithopods",
    meaning: "Lizard from Yandu",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "1.5m",
  },
  {
    name: "Agilisaurus",
    location: "China",
    type: "Ornithopods",
    meaning: "Fast Lizard",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "1.2m",
  },
  {
    name: "Xiaosaurus",
    location: "China",
    type: "Ornithopods",
    meaning: "Small Lizard",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "1m",
  },
  {
    name: "Alocodon",
    location: "Portugal",
    type: "Ornithopods",
    meaning: "Furrowed Tooth",
    period: "Middle Jurassic",
    diet: "Plants",
    size: "1m",
  },
];
